USE schedule;

CREATE TABLE user
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '유저 식별자',
    name VARCHAR(100) NOT NULL COMMENT '이름',
    email VARCHAR(100) COMMENT '이메일',
    is_deleted BOOLEAN NOT NULL DEFAULT 0 COMMENT '삭제여부',
    reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    mod_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);

CREATE TABLE schedule
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    author_id BIGINT NOT NULL COMMENT '작성자',
    todo VARCHAR(1000) NOT NULL COMMENT '할일',
    password VARCHAR(100) NOT NULL COMMENT '비밀번호',
    is_deleted BOOLEAN NOT NULL DEFAULT 0 COMMENT '삭제여부',
    reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    mod_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    FOREIGN KEY (author_id) REFERENCES user(id)
);
